/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *backspace;
  GtkWidget *Seveen;
  GtkWidget *plusminous;
  GtkWidget *clearscreen;
  GtkWidget *clear;
  GtkWidget *eight;
  GtkWidget *nine;
  GtkWidget *division;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *one;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *substraction;
  GtkWidget *mul;
  GtkWidget *add;
  GtkWidget *equall;
  GtkWidget *dot;
  GtkWidget *zero;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Biswaranjan"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 254, 300);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 120, 48);
  gtk_widget_set_size_request (entry1, 454, 52);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  backspace = gtk_button_new_with_mnemonic (_("Bksp"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 48, 128);
  gtk_widget_set_size_request (backspace, 102, 40);

  Seveen = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (Seveen);
  gtk_fixed_put (GTK_FIXED (fixed1), Seveen, 48, 232);
  gtk_widget_set_size_request (Seveen, 101, 40);

  plusminous = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (plusminous);
  gtk_fixed_put (GTK_FIXED (fixed1), plusminous, 528, 128);
  gtk_widget_set_size_request (plusminous, 102, 40);

  clearscreen = gtk_button_new_with_mnemonic (_("CLr"));
  gtk_widget_show (clearscreen);
  gtk_fixed_put (GTK_FIXED (fixed1), clearscreen, 368, 128);
  gtk_widget_set_size_request (clearscreen, 102, 40);

  clear = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 208, 128);
  gtk_widget_set_size_request (clear, 101, 40);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 208, 232);
  gtk_widget_set_size_request (eight, 102, 40);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 368, 232);
  gtk_widget_set_size_request (nine, 102, 40);

  division = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (division);
  gtk_fixed_put (GTK_FIXED (fixed1), division, 528, 232);
  gtk_widget_set_size_request (division, 102, 40);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 48, 328);
  gtk_widget_set_size_request (four, 98, 40);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 208, 328);
  gtk_widget_set_size_request (five, 106, 40);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 368, 320);
  gtk_widget_set_size_request (six, 104, 40);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 48, 424);
  gtk_widget_set_size_request (one, 105, 40);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 208, 424);
  gtk_widget_set_size_request (two, 105, 40);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 376, 424);
  gtk_widget_set_size_request (three, 104, 40);

  substraction = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (substraction);
  gtk_fixed_put (GTK_FIXED (fixed1), substraction, 528, 424);
  gtk_widget_set_size_request (substraction, 106, 40);

  mul = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed1), mul, 528, 320);
  gtk_widget_set_size_request (mul, 106, 40);

  add = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (add);
  gtk_fixed_put (GTK_FIXED (fixed1), add, 528, 520);
  gtk_widget_set_size_request (add, 106, 40);

  equall = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equall);
  gtk_fixed_put (GTK_FIXED (fixed1), equall, 384, 520);
  gtk_widget_set_size_request (equall, 105, 40);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 208, 520);
  gtk_widget_set_size_request (dot, 106, 40);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 48, 520);
  gtk_widget_set_size_request (zero, 104, 40);

  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) Seveen, "clicked",
                    G_CALLBACK (on_Seveen_clicked),
                    NULL);
  g_signal_connect ((gpointer) plusminous, "clicked",
                    G_CALLBACK (on_plusminous_clicked),
                    NULL);
  g_signal_connect ((gpointer) clearscreen, "clicked",
                    G_CALLBACK (on_clearscreen_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) division, "clicked",
                    G_CALLBACK (on_division_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) substraction, "clicked",
                    G_CALLBACK (on_substraction_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) add, "clicked",
                    G_CALLBACK (on_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) equall, "clicked",
                    G_CALLBACK (on_equall_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");
  GLADE_HOOKUP_OBJECT (window1, Seveen, "Seveen");
  GLADE_HOOKUP_OBJECT (window1, plusminous, "plusminous");
  GLADE_HOOKUP_OBJECT (window1, clearscreen, "clearscreen");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, division, "division");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, substraction, "substraction");
  GLADE_HOOKUP_OBJECT (window1, mul, "mul");
  GLADE_HOOKUP_OBJECT (window1, add, "add");
  GLADE_HOOKUP_OBJECT (window1, equall, "equall");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");

  return window1;
}

